#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 60553 Outline
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\setlength{\headheight}{10.2pt}
#+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2016 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\chead{\bf{Introduction to Chemical Engineering (CBE 20255)\vspace{12pt}}}
#+LATEX_HEADER:\lhead{\bf{Homework 5}}
#+LATEX_HEADER:\rhead{\bf{Due March 2, 2016}}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\title{University of Notre Dame\\Introduction to Chemical Engineering\\(CBE 20255)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\usepackage{siunitx}

#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

\noindent *Solve each problem on a separate sheets of Engineering Computation paper.  Carefully and neatly document your answers. Box your final answer, reporting it with the correct number of significant figures and units.  Use plotting software for all plots.*

* Key ideas :no_export:
- density of mixture (H2SO4/H2O)
- ideal gas, ideal gas mixture
- Real gas, compute pressure using ideal and SRK
- Compressibility

* Looking for the ideal solution..
Sulfuric acid (\ce{H2SO4}) is an important commodity chemical, used in various forms from dilute aqueous to neat (100%).  Because it is so important, its physical properties are well known and tabulated.  Perry's Handbook (available in the library or through the library [[http://onesearch.library.nd.edu/NDU:ebook:ndu_aleph003064056][website]]) provides a tabulation of the density of \ce{H2SO4}/\ce{H2O} solutions as a function of weight fraction for a range of temperatures.  (You'll want to write a Matlab program or use a spreadsheet to solve this one.)

1. (6 pts) Make a plot of 1/density vs.\nbsp{}wt% \ce{H2SO4} in water at \SI{25}{\celsius} from 0 to 100% in 5% increments.
2. (6 pts) Make a plot of molar volume (volume/mole of solution) vs.\nbsp{}mole fraction \ce{H2SO4} in water at \SI{25}{\celsius}.
3. (2 pts) Do sulfuric acid and water make an ideal of non-ideal solution?  If non-ideal, does it deviate positively or negatively from ideality?

* ...and I found it.
An ideal gas mixture contains 35%(v/v) He, 20%(v/v) methane, and 45%(v/v) \ce{N2} at 2.00 atm absolute and \SI{90}{\celsius}.

1. (2 pts) What is the partial pressure of each component?
2. (2 pts) What is the molar volume of the mixture, in l/mol?
3. (2 pts) How many SCM (standard cubic meters) does 100\bar{0} l of this gas mixture occupy?
4. (2 pts) What is the mass in kg of 100\bar{0} l of this gas mixture?
# 5. (4 pts) Look up and report the critical constants of He, \ce{CH4}, and \ce{N2}.  Is it reasonable to expect this mixture to be ideal?  Explain your answer.


* NO, NO, and still NO!
Some chemical reactions are limited by chemical equilibrium.  One prime example is NO(g) oxidation:

\[ \ce{NO (g) + 1/2 O2 (g) <=> NO2 (g)} \]

\noindent The /equilibrium constant/ \(K_{p}\) relates the proportions of reactants and products present at chemical equilibrium.  For NO oxidation the equilibrium constant can be written

\[ K_{p} = \frac{p_{\ce{NO2}}}{p_{\ce{NO}}p_{\ce{O2}}^{0.5}}\]

\noindent where \(p_{i}\) are the partial pressures of the components at equilibrium.

NO oxidation is carried out in a batch reactor at constant temperature
(isothermal).  The reactor is filled with 20.0%(v/v) NO and balance air at 380
kPa (absolute).  At the conditions of the experiment, all the gases can be taken
to be ideal.

1. (4 pts) What is the composition of the gas mixture when the NO conversion is 90%?
2. (2 pts) What is the total pressure in the batch reaction when the NO conversion is 90%?
3. (4 pts) When the NO oxidation reaction comes to equilibrium, the total pressure in the reactor is 360 kPa.  What are the partial pressures of all the components at this point?
4. (2 pts)  Calculate the NO oxidation equilibrium constant, \(K_{p}\).

5. (4 pts) Assuming \(K_{p}\) only depends on temperature, estimate the final pressure and composition in the reactor if equal molar amounts of NO and \ce{O2} are introduced to the reactor at 380 kPa (absolute).

* Don't be so critical
1. (4 pts) Look up the critical constants of methane, ethane, and propane, and butane.  Report on any trend you observe.
2. (3 pts) Which of these gases is most "ideal?"  Give two reasons why.

* A non-ideal state of affairs
A \SI{5.0}{\meter\cubed} tank is charged with \SI{75.0}{\kilo\gram} of propane at \SI{25}{\celsius}.

1. (2 pts) What does the ideal gas equation of state predict for the pressure in the tank?
2. (4 pts) How about the van der Waals equation of state?
3. (4 pts) How about the Soave-Redlich-Kwong equation of state?  (Note the Pitzer acentric factor of propane is \(\omega = 0.152\).)
4. (2 pts) Compute the reduced temperature and reduced volume of the propane.
5. (4 pts) Refer to a generalized compressibility chart to estimate the pressure and the compressibility of the propane in the tank.
