#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 60553 Outline
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\setlength{\headheight}{10.2pt}
#+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2016 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\chead{\bf{Introduction to Chemical Engineering (CBE 20255)\vspace{12pt}}}
#+LATEX_HEADER:\lhead{\bf{Homework 2}}
#+LATEX_HEADER:\rhead{\bf{Due January 29, 2016}}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\title{University of Notre Dame\\Introduction to Chemical Engineering\\(CBE 20255)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\usepackage{siunitx}

#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

\noindent *Solve each problem on a separate sheets of Engineering Computation paper.  Carefully and neatly document your answers. Box your final answer, reporting it with the correct number of significant figures and units.  Use plotting software for all plots.*

* Key ideas :no_export:
- statistics
- density
- flow rates
- chemical compositions
- mixtures

* That's where I draw the line.
In homework 1, you learned about a solution containing hazardous waste that is charged into a storage tank and subjected to a treatment that decomposes the waste into harmless products.  The concentration of the decomposing waste (\(C_{W}\)) is reported to vary according to the model

\[ C_{W} = 1/(a + bt) \]

\noindent When \(C_{W}\) decreases to \(< \SI{0.01}{\g\per\L}\) the contents of the tank are discharged appropriately.  The following are some data for \(C_{W}\) vs. /t/:

| /t/ (hr)        |  1.0 |  2.0 |  3.0 |  4.0 |  5.0 |
|-----------------+------+------+------+------+------|
| \(C_{W}\) (g/L) | 1.43 | 1.02 | 0.73 | 0.53 | 0.38 |

1. (4\nbsp{}pts) Suggest a linearization of the model (a rearrangement that allows the data to
   be plotted to fit a straight line).  Plot the linearized data on a new graph,
   again using good plotting practices.
2. (4\nbsp{}pts) Use the method of least squares to estimate the values of /a/
   and /b/ from the data (remember to include appropriate units!).  Plot the
   line on the same graph as the linearized data.
3. (4\nbsp{}pts) Use the fitted model to estimate the initial value of \(C_{W}\)
   and the time necessary for \(C_{W}\) to reach the discharge concentration.
4. (2\nbsp{}pts) How much faith do you have in this time estimate?  Why?


* Can't take take the heat
Two thermocouples are tested by inserting their probes into boiling \ce{H2O}, recording readings, drying, and repeating.  Here's the results:

#+ATTR_LATEX: :align l|cccccccc
|-----------------------------------+------+-------+------+-------+-------+------+------+------|
| T (\si{\celsius}) Thermocouple A: | 72.4 |  73.1 | 72.6 |  72.8 |  73.0 | 73.2 | 72.6 | 72.5 |
| T (\si{\celsius}) Thermocouple B: | 97.3 | 101.4 | 98.7 | 103.1 | 100.4 | 99.9 | 98.2 | 99.6 |
|-----------------------------------+------+-------+------+-------+-------+------+------+------|

1. (4\nbsp{}pts) Construct a /histogram/ of each data set, using an appropriate bin width in each case. (Recall a histogram is a bar plot of the number of data points within a series of bins.)

2. (6\nbsp{}pts) Compute the mean, range, and standard deviation of each data set.

3. (2\nbsp{}pts) Which thermocouple is more /precise/ (shows least scatter)?  Which is more /accurate/?

4. (1\nbsp{}pts) Which would you choose to use if you needed to get a quick estimate of the temperature of some other boiling fluid?

5. (1\nbsp{}pts) Which would you choose to use on a process control unit designed to hold the temperature of a bath at \SI{100.}{\celsius}?


* A pipe runs through it
A 10.00%(w/w) aqueous nitric acid solution (\rho = 1.03 g/ml) flows through a \SI{45}{\meter} long pipe with a 6.0 cm diameter at a rate of 82 L/min.

1. (2\nbsp{}pts) What is the molarity of the nitric acid solution?

2. (2\nbsp{}pts) How long in seconds would it take to fill a 55-gal drum?

3. (2\nbsp{}pts) How much nitric acid would the drum contain, in kg?

4. (2\nbsp{}pts) How long does it take for a bit of nitric acid solution to make it from the inlet to the outlet of the pipe?

* Chill out, man
A gas stream contains 18.0 mole % hexane and balance of nitrogen.  The stream flows through a condensor, where it is chilled to room temperature and some of the hexane is removed as a pure liquid condensate, at a rate of 1.50 L/min.  The gas leaving the condensor contains 5.00 mole % hexane.

1. (4\nbsp{}pts) Draw a diagram of this system.  Indicate the condensor as a box, and use arrows to label all the inlet and exit streams along with whatever information you have about each stream.

2. (4\nbsp{}pts) Compute the molar flow rate of the condensate.  (/Note/: You need to know a physical property of hexane that I didn't tell you.  Look it up in Perry's Handbook or a similar resource.)

3. (6\nbsp{}pts) What is the molar flow rate of the gas stream leaving the condensor?  (/Hint/: What must be true about the total molar flow rate of nitrogen into and out of the condensor?  How about hexane?)

4. (4\nbsp{}pts) What percent (by moles) of hexane is recovered as liquid?

5. (4\nbsp{}pts) Suggest two different process modifications you could make to increase the amount of hexane recovered.

\noindent Congratulations!  You just did your first mass balance!
