#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 20255 Syllabus
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
# #+LATEX_HEADER:\setlength{\headheight}{10.2pt}
# #+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2016 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\title{University of Notre Dame\\Advanced Chemical Engineering Thermodynamics\\(CBE 60553)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsection}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsubsection}
#+LATEX_HEADER:{0pt}{0.4\baselineskip}{0.1\baselineskip}

#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

#+BEGIN_LaTeX
\begin{center}
\textsc{\Large Introduction to Chemical Engineering (CBE 20255)}\\University of Notre Dame, Spring 2016
\end{center}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}l r}
\hline
Prof.\ Bill Schneider & Classroom: 356A Fitz.\\
Office: 123b Cushing & Lecture MWF 10:30-11:20\\
\email{wschneider@nd.edu}, phone 574-631-8754 & Tutorial M 3:30-4:20\\
\hline
\end{tabular*}
#+END_LaTeX

* Introduction to Chemical Engineering
Welcome to your first course in Chemical Engineering!  Engineering is a way of
thinking: a problem-solving, goal-oriented mindset founded on sound
quantitative, scientific concepts. In Chemical Engineering, those concepts
primarily involve chemical processes: processes that involve moving stuff
around, mixing it up, reacting it, separating it, heating or cooling it---as
happens in engineered chemical systems as small as a microbe and as large as a
petroleum refinery. These are all topics you will learn about in the three core
Chemical Engineering courses: Thermodynamics, Transport, and Reactions.  To get
you prepared, first you must become familiar with the terminology, basic problem
solving techniques, and core concepts and applications of mass and energy
conservation ("balances").  That is what this course is about.

Chemical Engineering is a concept-rich field and a demanding course of study.
Good study habits start now.  I strongly encourage you to keep up with the
reading and homework and to feel welcome to ask questions in class.  Don't be
bashful: if you don't understand something, chances are some of your classmates
(and perhaps even your instructor!) don't either.

* Text
Richard M. Felder, Roger W. Rousseau, Lisa G. Bullard, "Elementary Principles of Chemical Processes," Wiley, 3rd or 4th ed.


* Topics :no_export:
| Topic                         | Reading |
|-------------------------------+---------|
| What is Chemical Engineering? | Ch. 1   |
| Engineering Calculations      | Ch. 2   |

* Lecture and Tutorial
The topics and example problems will be covered during lecture.  Attendance is
expected, and you should be prepared to ask and answer questions.  The tutorial
period is a time for you to ask questions of the Instructor and TA, work with
your classmates, and get assistance with homework assignments. Attendance is
optional, other than for the three quizzes that are scheduled during the
tutorial periods.

* Homework
Ten graded problem sets will be distributed during the semester and will be due at the beginning of class on dates to be announced.  *Assignments turned in late will automatically lose 20%, and those turned in after the solutions are posted will not be accepted.*  Your two lowest scores on homework will be dropped.  You may discuss the homework with your classmates, but *what you turn in must be your own work.*

* Homework Defense
To help me get to know you and how you are doing with the course, after each homework assignment three of you will be chosen at random to meet with me one-on-one to defend their homework answers.

* Tutorial :no_export:
The tutorial period is a time for you to ask questions of the Instructor and TA, work with your classmates, and get assistance with homework assignments. Attendance is optional, other than for the three quizzes that are scheduled during the tutorial periods.

* Grading
Grades will be based on the homework (25%), two in-class exams (30%), three tutorial quizzes (15%), and a cumulative final (30%).

* Web
This syllabus, reading assignment, the homework assignments and solutions, and a summary of the lecture schedule with any useful supplementary material is available on the web at http://www.nd.edu/~wschnei1/courses.shtml.

* Academic honesty
Should go without saying. Any cheating or misrepresenting of work as your own will be dealt with according to the Honor Code policies of the university. I reserve the right to relocate any students during an examination at my discretion.

* Professional courtesy
As a courtesy to the instructor and your classmates, please refrain from
texting, web browsing, tweeting, updating, or using your phone or laptop for any
purpose during class time.  If you must use an electronic device, excuse
yourself from class.

* Office hours
The TA and instructor are happy to answer questions during regular office hours or by appointment if you need extra help.

| Dr. Bill Schneider\quad\quad | Mr. Sichi Li, \email{sli12@nd.edu} |
| 123a Cushing                 | 150 Fitz                           |
| M, 4-5 pm                    | W, 4-5 pm                          |


* Course Calendar
(subject to revision)
|----------+----------+----------+----------------------+----------+--------------+---------------|
|          | 1/13     | 1/15     | \quad\quad\quad\quad | 3/14     | 3/16         | 3/18          |
|          | Welcome! |          |                      | /Quiz 2/ | *HW 6*       |               |
|----------+----------+----------+----------------------+----------+--------------+---------------|
| 1/18     | 1/20     | 1/22     |                      | 3/21     | 3/23         | 3/25          |
| Tutorial | *HW 1*   |          |                      | Tutorial | *Exam 2*     | *Good Friday* |
|----------+----------+----------+----------------------+----------+--------------+---------------|
| 1/25     | 1/27     | 1/29     |                      | 3/28     | 3/30         | 4/1           |
| Tutorial |          | *HW 2*   |                      | *Easter* |              | *HW 7*        |
|----------+----------+----------+----------------------+----------+--------------+---------------|
| 2/1      | 2/3      | 2/5      |                      | 4/4      | 4/6          | 4/8           |
| /Quiz 1/ |          |          |                      | Tutorial |              |               |
|----------+----------+----------+----------------------+----------+--------------+---------------|
| 2/8      | 2/10     | 2/12     |                      | 4/11     | 4/13         | 4/15          |
| *HW 3*   |          | *Exam 1* |                      | *HW 8*   |              |               |
| Tutorial |          |          |                      | Tutorial |              |               |
|----------+----------+----------+----------------------+----------+--------------+---------------|
| 2/15     | 2/17     | 2/19     |                      | 4/18     | 4/20         | 4/22          |
| Tutorial |          |          |                      | /Quiz 3/ | *HW 9*       |               |
|----------+----------+----------+----------------------+----------+--------------+---------------|
| 2/22     | 2/24     | 2/26     |                      | 4/25     | 4/27         | 4/29          |
| *HW 4*   |          |          |                      | Tutorial | *Last class* | *HW 10*       |
|----------+----------+----------+----------------------+----------+--------------+---------------|
| 2/29     | 3/2      | 3/4      |                      |          | *Final Exam* |               |
| Tutorial | *HW 5*   |          |                      |          | *TBD*        |               |
|----------+----------+----------+----------------------+----------+--------------+---------------|
| 3/7      | 3/9      | 3/11     |                      |          |              |               |
| *BREAK*  | *BREAK*  | *BREAK*  |                      |          |              |               |
|----------+----------+----------+----------------------+----------+--------------+---------------|
