#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 60553 Outline
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\setlength{\headheight}{10.2pt}
#+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2016 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\chead{\bf{Introduction to Chemical Engineering (CBE 20255)\vspace{12pt}}}
#+LATEX_HEADER:\lhead{\bf{Homework 3}}
#+LATEX_HEADER:\rhead{\bf{Due February 8, 2016}}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\title{University of Notre Dame\\Introduction to Chemical Engineering\\(CBE 20255)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\usepackage{siunitx}

#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

\noindent *Solve each problem on a separate sheets of Engineering Computation paper.  Carefully and neatly document your answers. Box your final answer, reporting it with the correct number of significant figures and units.  Use plotting software for all plots.*

* Key ideas :no_export:
- pressure
- mass balance
- mass balance

* [[https://www.youtube.com/watch?v=YoDh_gHDvkk][Under Pressure (in memory of Bowie and, of course, Mercury!)]]
Two mercury manometers, one open-ended and one sealed, are attached to an air duct.  The open-end manometer reads 22 mm and the sealed end 800 mm.

1. (4 pts) What is the absolute pressure in the duct, in mmHg and in atm?

2. (4 pts) What is the gauge pressure in the duct, in mmHg and in Pa?

3. (4 pts) What is the atmospheric pressure, in mmHg and in psi?

* Fill me up
The liquid level in a tank is determined by measuring the pressure at the bottom of the tank.  A calibration curve is prepared by filling the tank to several known levels, reading the bottom pressure using a [[https://en.wikipedia.org/wiki/Pressure_measurement#Bourdon][Bourdon gauge]], and plotting level in m vs.\nbsp{}pressure in bar.

1. (4 pts) Make a sketch of what you expect the calibration curve to look like.  You can do this by hand, but label axes and make sure all important parts of your curve are clear.

2. (4 pts) The calibration was done with a fluid that has a specific gravity of 0.900, but the tank is actually used to store a fluid with a specific gravity of 0.800.  Make a sketch of the actual fluid height vs.\nbsp{}the calibration-curve-predicted height.  Again, you can do this by hand, but pay careful attention to indicate all important features of your curve.

3. (6 pts) The tank is \SI{10}{\meter} tall. What will the Bourdon gauge read (assuming it is working correctly) when the tank overflows, and what will the calibration curve /say/ that the liquid height is?

* Achieving (mol) balance
A process stream contains 44.6%(mol/mol) benzene and 55.4%(mol/mol) toluene and is fed to a process unit that separates these into a liquid and a vapor stream.  When the unit is started up, the initial vapor flow rate is zero, but it then gradually rises and asymptotically approaches half the total molar flow rate.  No material accumulates in the process unit throughout or after start-up.  After the vapor flow rate becomes constant, the liquid phase is analyzed and found to contain 28.0%(mol/mol) benzene.

1. (4 pts) Make a sketch of the liquid and vapor flow rates vs.\nbsp{}time, from start-up until the vapor flow rate is constant.  You can do this by hand, but label axes and make sure all important parts of your curve are clear.
2. (1 pt) Is this process continuous or batch?
3. (2 pt) Is the process transient or steady-state when first started up?  When the vapor stream attains a constant flow rate?
4. (4 pts) Assuming that the feed rate is 100 mol/min, draw and *fully label* a flowchart for the process after the vapor flow rate has become constant.
5. (4 pts) Use balances to compute the vapor phase composition after the vapor flow rate has become constant.

* Achieving (mass) balance
Soybean oil is extracted from soy beans by first drying and chopping up the beans, and then "extracting" the oil from the beans by contacting them with a solvent (like hexane) that draws the oil out and leaves behind the residual bean solids (plus some remaining soybean oil).

1. (6 pts) The soybeans contain 18.5%(w/w) oil and balance insoluble solids, and the hexane is fed at a mass flow rate twice that of the beans.  The residual solids stream contains 35.5%(w/w) hexane, all the insoluble solids, and 1.0%(w/w) soybean oil.  Dried soybeans are fed at a rate of 1000 kg/hr.  Draw a flowchart of the extraction process, labeling the two input streams (beans and hexane), the two output streams (solids and extract), the known and unknown flow rates, and the known and unknown stream compositions.

2. (6 pts) Calculate all unknown mass flow rates and all unknown mass compositions.

3. (4 pts) After the extraction, the soybean oil must be separated from the hexane.  Sketch a flowchart for such a process.  What would you do with the recovered hexane?

* Get in line
Two distillation columns are connected in series.  A liquid mixture containing 30.0, 25.0, and 45.0 %(mol/mol) of benzene (B), toluene (T), and xylene (X), respectively, are fed to the first column.  The bottom of the first column collects 96.0% of the input xylene in a stream that contains 98.0% xylene and balance toluene.  The top of the first column is fed to the second column.  The top of the second column recovers 97.0% of the benzene fed to this column in a stream that is 94.0% benzene and balance toluene.

1. (6 pts) Draw a process diagram and label all known and unknown flow rates and compositions.  Draw boxes around the parts of the process about which it is possible to do a mass balance.

2. (2 pts) If the flow rate into the first column is known, is it possible to determine the three flow rates out of the overall process?  Use a degree of freedom analysis.

2. (6 pts) Perform a mass balance on the first column.  What is the composition of the stream entering the second column?

3. (6 pts) Perform a mass balance on the second column.  What are the compositions of the stream leaving it?

4. (6 pts) How effective overall is the separation?  That is, what fraction of the benzene entering the first column is recovered out the top of the second?  What fraction of toluene entering the first column is recovered out the bottom of the second?


* Calibrate me :no_export:
An "orifice meter" is a device for inferring flow rates from the pressure drop across a constriction in a pipe (see the diagram below).  You are tasked with calibrating an orifice meter to determine the flow rate of a liquid acetone stream.  The manometer across the constriction is filled with a fluid that has a specific gravity of 1.10.  You use a value and a previously calibrated rotameter to adjust the flow rate through the orifice and observe the manometer reading.  Here's the data:

|-------------------+--------------------|
| Manometer Reading |          Flow Rate |
|          /h/ (mm) | \(\dot{V}\) (mL/s) |
|-------------------+--------------------|
|                 0 |                  0 |
|                 5 |                 62 |
|                10 |                 87 |
|                15 |                107 |
|                20 |                123 |
|                25 |                138 |
|                30 |                151 |
|-------------------+--------------------|

1.

* [[https://www.youtube.com/watch?v=1d3tfCRfztY][There She Goes Again]] :no_export:
A student
